[package]
name = "digitalocean"
version = "0.0.2"
authors = ["hoverbear <andrew@hoverbear.org>"]
repository = "https://github.com/hoverbear/digitalocean"
categories = ["development-tools"]
homepage = "https://github.com/hoverbear/digitalocean"
documentation = "https://docs.rs/crate/digitalocean/"

keywords = ["DigitalOcean", "IaaS", "API"]
license = "MIT"
description = """
A crate for accessing and interacting with the DigitalOcean API.
"""

[features]
default = ["reqwest"]

[dependencies]
getset = "0.0.5"
error-chain = "0.11.0-rc.2"
lazy_static = "0.2.8"
log = "0.3.8"
reqwest = { version = "0.7.3", optional = true }
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
url = "1.5.1"
url_serde = "0.2.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dev-dependencies]
dotenv = "0.10.0"
env_logger = "0.4.3"

[dev-dependencies.uuid]
features = ["v4"]
version = "0.5"
