[package]
authors = ["hoverbear <andrew@hoverbear.org>"]
name = "digitalocean"
version = "0.1.0"
description = "A crate for interfacing with Digital Ocean's V2 API."
documentation = ""
homepage = "https://github.com/hoverbear/digitalocean"
repository = "https://github.com/hoverbear/digitalocean"
keywords = ["DigitalOcean", "IaaS", "Provisioning"]
categories = ["development-tools"]
license = "MIT"

[dependencies]
error-chain = "0.10.0"
lazy_static = "0.2.5"
log = "0.3.7"
reqwest = "0.5.1"
serde = "0.9.12"
serde_derive = "0.9.12"
serde_json = "0.9.9"
url = "1.4.0"
url_serde = "0.1.3"

[dev-dependencies]
dotenv = "0.10.0"
env_logger = "0.4.2"

[dev-dependencies.uuid]
features = ["v4"]
version = "0.4"
