[package]
name = "digitalocean"
version = "0.1.0"
authors = ["hoverbear <andrew@hoverbear.org>"]
repository = "https://github.com/hoverbear/digitalocean"
categories = ["development-tools"]
description = "A crate for interfacing with Digital Ocean."
homepage = "https://github.com/hoverbear/digitalocean"
keywords = ["DigitalOcean", "IaaS", "API"]
license = "MIT"
documentation = ""

[features]
default = ["reqwest"]

[dependencies]
error-chain = "0.10.0"
lazy_static = "0.2.5"
log = "0.3.7"
reqwest = { version = "0.6.0", optional = true }
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
url = "1.4.0"
url_serde = "0.2.0"

[dependencies.chrono]
features = ["serde"]
version = "0.3.0"

[dev-dependencies]
dotenv = "0.10.0"
env_logger = "0.4.2"

[dev-dependencies.uuid]
features = ["v4"]
version = "0.4"