[package]
name = "digitalocean"
version = "0.1.0"
authors = ["hoverbear <andrew@hoverbear.org>"]

[dependencies]
lazy_static = "0.2.5"
log = "0.3.7"
reqwest = "0.5.1"
serde = "0.9.12"
serde_derive = "0.9.12"
serde_json = "0.9.9"
url_serde = "0.1.3"
url = "1.4.0"

[dev-dependencies]
dotenv = "0.10.0"
env_logger = "0.4.2"

[dev-dependencies.uuid]
features = ["v4"]
version = "0.4"
